# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai_interface.proto',
  package='ai_analysis',
  syntax='proto3',
  serialized_options=b'\n\023io.grpc.ai_analysisB\021ai_analysis_protoP\001\242\002\003AAP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x61i_interface.proto\x12\x0b\x61i_analysis\"(\n\nCoordinate\x12\x0c\n\x04posX\x18\x01 \x01(\x05\x12\x0c\n\x04posY\x18\x02 \x01(\x05\">\n\x04\x42\x62ox\x12\x0c\n\x04xMin\x18\x01 \x01(\x05\x12\x0c\n\x04yMin\x18\x02 \x01(\x05\x12\x0c\n\x04xMax\x18\x03 \x01(\x05\x12\x0c\n\x04yMax\x18\x04 \x01(\x05\"=\n\x04\x41rea\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x06\x62order\x18\x02 \x03(\x0b\x32\x17.ai_analysis.Coordinate\"w\n\x11PreProcessingData\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\'\n\x0cwarning_list\x18\x02 \x03(\x0b\x32\x11.ai_analysis.Area\x12&\n\x0b\x64\x61nger_list\x18\x03 \x03(\x0b\x32\x11.ai_analysis.Area\"\x9b\x01\n\x0cTrackingData\x12\x1f\n\x04\x62\x62ox\x18\x01 \x01(\x0b\x32\x11.ai_analysis.Bbox\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x12\n\nequiqments\x18\x03 \x03(\t\x12\x0f\n\x07time_in\x18\x04 \x01(\t\x12\x11\n\tarea_name\x18\x05 \x01(\t\x12\x0f\n\x07warning\x18\x06 \x01(\x08\x12\x0e\n\x06\x64\x61nger\x18\x07 \x01(\x08\"J\n\rProcessedData\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12*\n\x07persons\x18\x02 \x03(\x0b\x32\x19.ai_analysis.TrackingData\"\x1d\n\x08\x43\x61meraId\x12\x11\n\tcamera_id\x18\x01 \x01(\t\"r\n\nCameraInfo\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\t\x12\x0b\n\x03uri\x18\x06 \x01(\t\"0\n\x0c\x43\x61meraResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdd\x01\n\x0c\x41nalyService\x12\x41\n\tAddCamera\x12\x17.ai_analysis.CameraInfo\x1a\x19.ai_analysis.CameraResult\"\x00\x12?\n\tDelCamera\x12\x15.ai_analysis.CameraId\x1a\x19.ai_analysis.CameraResult\"\x00\x12I\n\tGetFrames\x12\x1e.ai_analysis.PreProcessingData\x1a\x1a.ai_analysis.ProcessedData\"\x00\x42\x30\n\x13io.grpc.ai_analysisB\x11\x61i_analysis_protoP\x01\xa2\x02\x03\x41\x41Pb\x06proto3'
)




_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='ai_analysis.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='posX', full_name='ai_analysis.Coordinate.posX', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='posY', full_name='ai_analysis.Coordinate.posY', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=75,
)


_BBOX = _descriptor.Descriptor(
  name='Bbox',
  full_name='ai_analysis.Bbox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xMin', full_name='ai_analysis.Bbox.xMin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yMin', full_name='ai_analysis.Bbox.yMin', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xMax', full_name='ai_analysis.Bbox.xMax', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yMax', full_name='ai_analysis.Bbox.yMax', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=139,
)


_AREA = _descriptor.Descriptor(
  name='Area',
  full_name='ai_analysis.Area',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai_analysis.Area.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='border', full_name='ai_analysis.Area.border', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=202,
)


_PREPROCESSINGDATA = _descriptor.Descriptor(
  name='PreProcessingData',
  full_name='ai_analysis.PreProcessingData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='ai_analysis.PreProcessingData.camera_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warning_list', full_name='ai_analysis.PreProcessingData.warning_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='danger_list', full_name='ai_analysis.PreProcessingData.danger_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=323,
)


_TRACKINGDATA = _descriptor.Descriptor(
  name='TrackingData',
  full_name='ai_analysis.TrackingData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bbox', full_name='ai_analysis.TrackingData.bbox', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person_id', full_name='ai_analysis.TrackingData.person_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equiqments', full_name='ai_analysis.TrackingData.equiqments', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_in', full_name='ai_analysis.TrackingData.time_in', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='area_name', full_name='ai_analysis.TrackingData.area_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warning', full_name='ai_analysis.TrackingData.warning', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='danger', full_name='ai_analysis.TrackingData.danger', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=481,
)


_PROCESSEDDATA = _descriptor.Descriptor(
  name='ProcessedData',
  full_name='ai_analysis.ProcessedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='ai_analysis.ProcessedData.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='persons', full_name='ai_analysis.ProcessedData.persons', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=557,
)


_CAMERAID = _descriptor.Descriptor(
  name='CameraId',
  full_name='ai_analysis.CameraId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='ai_analysis.CameraId.camera_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=588,
)


_CAMERAINFO = _descriptor.Descriptor(
  name='CameraInfo',
  full_name='ai_analysis.CameraInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='ai_analysis.CameraInfo.camera_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='ai_analysis.CameraInfo.location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='ai_analysis.CameraInfo.coordinates', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='ai_analysis.CameraInfo.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='ai_analysis.CameraInfo.port', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='ai_analysis.CameraInfo.uri', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=590,
  serialized_end=704,
)


_CAMERARESULT = _descriptor.Descriptor(
  name='CameraResult',
  full_name='ai_analysis.CameraResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ai_analysis.CameraResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ai_analysis.CameraResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=706,
  serialized_end=754,
)

_AREA.fields_by_name['border'].message_type = _COORDINATE
_PREPROCESSINGDATA.fields_by_name['warning_list'].message_type = _AREA
_PREPROCESSINGDATA.fields_by_name['danger_list'].message_type = _AREA
_TRACKINGDATA.fields_by_name['bbox'].message_type = _BBOX
_PROCESSEDDATA.fields_by_name['persons'].message_type = _TRACKINGDATA
DESCRIPTOR.message_types_by_name['Coordinate'] = _COORDINATE
DESCRIPTOR.message_types_by_name['Bbox'] = _BBOX
DESCRIPTOR.message_types_by_name['Area'] = _AREA
DESCRIPTOR.message_types_by_name['PreProcessingData'] = _PREPROCESSINGDATA
DESCRIPTOR.message_types_by_name['TrackingData'] = _TRACKINGDATA
DESCRIPTOR.message_types_by_name['ProcessedData'] = _PROCESSEDDATA
DESCRIPTOR.message_types_by_name['CameraId'] = _CAMERAID
DESCRIPTOR.message_types_by_name['CameraInfo'] = _CAMERAINFO
DESCRIPTOR.message_types_by_name['CameraResult'] = _CAMERARESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATE,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.Coordinate)
  })
_sym_db.RegisterMessage(Coordinate)

Bbox = _reflection.GeneratedProtocolMessageType('Bbox', (_message.Message,), {
  'DESCRIPTOR' : _BBOX,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.Bbox)
  })
_sym_db.RegisterMessage(Bbox)

Area = _reflection.GeneratedProtocolMessageType('Area', (_message.Message,), {
  'DESCRIPTOR' : _AREA,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.Area)
  })
_sym_db.RegisterMessage(Area)

PreProcessingData = _reflection.GeneratedProtocolMessageType('PreProcessingData', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSINGDATA,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.PreProcessingData)
  })
_sym_db.RegisterMessage(PreProcessingData)

TrackingData = _reflection.GeneratedProtocolMessageType('TrackingData', (_message.Message,), {
  'DESCRIPTOR' : _TRACKINGDATA,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.TrackingData)
  })
_sym_db.RegisterMessage(TrackingData)

ProcessedData = _reflection.GeneratedProtocolMessageType('ProcessedData', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSEDDATA,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.ProcessedData)
  })
_sym_db.RegisterMessage(ProcessedData)

CameraId = _reflection.GeneratedProtocolMessageType('CameraId', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAID,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.CameraId)
  })
_sym_db.RegisterMessage(CameraId)

CameraInfo = _reflection.GeneratedProtocolMessageType('CameraInfo', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAINFO,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.CameraInfo)
  })
_sym_db.RegisterMessage(CameraInfo)

CameraResult = _reflection.GeneratedProtocolMessageType('CameraResult', (_message.Message,), {
  'DESCRIPTOR' : _CAMERARESULT,
  '__module__' : 'ai_interface_pb2'
  # @@protoc_insertion_point(class_scope:ai_analysis.CameraResult)
  })
_sym_db.RegisterMessage(CameraResult)


DESCRIPTOR._options = None

_ANALYSERVICE = _descriptor.ServiceDescriptor(
  name='AnalyService',
  full_name='ai_analysis.AnalyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=757,
  serialized_end=978,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddCamera',
    full_name='ai_analysis.AnalyService.AddCamera',
    index=0,
    containing_service=None,
    input_type=_CAMERAINFO,
    output_type=_CAMERARESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DelCamera',
    full_name='ai_analysis.AnalyService.DelCamera',
    index=1,
    containing_service=None,
    input_type=_CAMERAID,
    output_type=_CAMERARESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrames',
    full_name='ai_analysis.AnalyService.GetFrames',
    index=2,
    containing_service=None,
    input_type=_PREPROCESSINGDATA,
    output_type=_PROCESSEDDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYSERVICE)

DESCRIPTOR.services_by_name['AnalyService'] = _ANALYSERVICE

# @@protoc_insertion_point(module_scope)
